name: SmallRye Prepare Release

on:
  pull_request:
    types: [ closed ]
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-release:
    name: Prepare Release
    if: ${{ github.event.pull_request.merged == true}}
    uses: smallrye/.github/.github/workflows/prepare-release.yml@394b0cc9f368ad0a6fadd1e98e71ec47984a3fde # main
    secrets: inherit