package io.smallrye.mutiny.vertx.apigenerator.shims;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.type.TypeParameter;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.TypeSpec;
import io.smallrye.mutiny.vertx.TypeArg;
import io.smallrye.mutiny.vertx.apigenerator.analysis.*;
import io.smallrye.mutiny.vertx.apigenerator.collection.VertxGenInterface;

import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.List;

/**
 * Declares the constructor taking the `delegate` as parameter as well a type args.
 */
public class DelegateAndTypeArgsConstructorShimModule implements ShimModule {
    @Override
    public boolean accept(ShimClass shim) {
        return shim.getSource().isConcrete();
    }

    @Override
    public void analyze(ShimClass shim) {
        if (shim.getSource().getTypeParameters().isEmpty()) {
            // Skip if no type parameters
            return;
        }
        // Need to determine the method parameters
        List<ShimMethodParameter> parameters = new ArrayList<>();
        parameters.add(new ShimMethodParameter("delegate", shim.getSource().getType(), null, false));
        int index = 0;
        for (TypeParameter tv : shim.getSource().getTypeParameters()) {
            parameters.add(new ShimMethodParameter("typeArg_" + index,
                    StaticJavaParser.parseClassOrInterfaceType(TypeArg.class.getName())
                            .setTypeArguments(StaticJavaParser.parseTypeParameter(tv.getNameAsString())),
                    null, false));
            index++;
        }
        shim.addConstructor(new DelegateAndTypeArgsConstructor(this, shim.getSource(), parameters));
    }

    private static class DelegateAndTypeArgsConstructor extends BaseShimConstructor {
        private final VertxGenInterface source;

        public DelegateAndTypeArgsConstructor(DelegateAndTypeArgsConstructorShimModule module,
                VertxGenInterface source,
                List<ShimMethodParameter> parameters) {
            super(module, parameters);
            this.source = source;
        }

        @Override
        public void generate(ShimClass shim, TypeSpec.Builder builder) {
            MethodSpec.Builder cst = MethodSpec.constructorBuilder();
            cst.addModifiers(Modifier.PUBLIC);
            for (ShimMethodParameter parameter : getParameters()) {
                var cn = Shim.getTypeNameFromType(parameter.shimType());
                var name = parameter.name();
                cst.addParameter(cn, name);
            }
            if (shim.getParentClass() != null) {
                cst.addStatement("super(delegate)");
            }
            cst.addComment("Generated by " + declaredBy().getClass().getName());
            cst.addStatement("this.delegate = delegate");
            int index = 0;
            for (TypeParameter tv : source.getTypeParameters()) {
                cst.addComment("Type parameter " + index + " : " + tv.getNameAsString());
                cst.addStatement("this.__typeArg_" + index + " = typeArg_" + index);
                index++;
            }
            builder.addMethod(cst.build());
        }

    }
}
